const INITIAL_CATALOG = [
    {
        WMS_ACAD_YEAR: '2020',
        OFFERED: 'Y',
        STRM: '1201',
        CRSE_ID: '020209',
        EFFDT: '01-SEP-19',
        SUBJECT: 'AFR',
        CATALOG_NBR: '105',
        CLASS_SECTION: '01',
        CLASS_NBR: '1089',
        CONSENT: 'N',
        GRADING_BASIS: 'OPT',
        SSR_COMPONENT: 'LEC',
        DESCR: 'African Art Survey',
        UNITS_MINIMUM: '1',
        COURSE_TITLE_LONG: 'Materials, Meanings, and Messages in the Arts of Africa',
        WMS_FIRST_NAME1: 'Michelle',
        WMS_MID_NAME1: 'M.',
        WMS_LAST_NAME1: 'Apotsos',
        URL_1: 'https://art.williams.edu/profile/ma11/',
        WMS_FIRST_NAME2: ' ',
        WMS_MID_NAME2: ' ',
        WMS_LAST_NAME2: ' ',
        URL_2: ' ',
        WMS_FIRST_NAME3: ' ',
        WMS_MID_NAME3: ' ',
        WMS_LAST_NAME3: ' ',
        URL_3: ' ',
        WMS_FIRST_NAME4: ' ',
        WMS_MID_NAME4: ' ',
        WMS_LAST_NAME4: ' ',
        URL_4: ' ',
        WMS_FIRST_NAME5: ' ',
        WMS_MID_NAME5: ' ',
        WMS_LAST_NAME5: ' ',
        URL_5: ' ',
        WMS_FIRST_NAME6: ' ',
        WMS_MID_NAME6: ' ',
        WMS_LAST_NAME6: ' ',
        URL_6: ' ',
        WMS_STND_MTG_PAT1: 'MW',
        WMS_START_TIME1: '11:00',
        WMS_END_TIME1: '12:15',
        WMS_FACIL_DESCR1: ' ',
        WMS_STND_MTG_PAT2: ' ',
        WMS_START_TIME2: ' ',
        WMS_END_TIME2: ' ',
        WMS_FACIL_DESCR2: ' ',
        WMS_STND_MTG_PAT3: ' ',
        WMS_START_TIME3: ' ',
        WMS_END_TIME3: ' ',
        WMS_FACIL_DESCR3: ' ',
        WMS_ATTR_SRCH: 'DIV_D2,DPE_DPE',
        WMS_CLASS_FORMAT: 'lecture',
        WMS_RQMT_EVAL:
            'three 2-page response papers, class journal on WCMA objects lab, midterm exam and final exam',
        WMS_EXTRA_INFO: ' ',
        WMS_EXTRA_INFO2: ' ',
        WMS_INSTR_OTH: ' ',
        WMS_PREREQS: 'none',
        WMS_ENRL_PREF: 'Art History and African Studies majors',
        WMS_DEPT_NOTES: ' ',
        WMS_MATL_FEE: ' ',
        WMS_EXP_ENRL: '40',
        WMS_ENRL_LIMIT: '40',
        WMS_NC: ' ',
        CAMPUS: 'WMS',
        WMS_DESCR140: ' ',
        WMS_SHORT_DESCR: null,
        WMS_DISTRIB_NT1: null,
        WMS_DISTRIB_NT2:
            "This course fulfills DPE requirements through its exploration of the differences between concepts of art in African and Western traditions, and how this difference has formed the foundation for hierarchies of power within the art world that have long disenfranchised and disempowered artists from the continent. This course highlights this historical platform in order to renovate established biases and assumptions about these objects that position them as 'primitive' or 'exotic' constructs.",
        WMS_DISTRIB_NT3: null,
        WMS_DESCR_SRCH:
            'This course introduces students to the wealth, power, and diversity of expressive forms that have characterized the arts of Africa and its Diaspora from prehistory to the present. Pulling extensively from the collections at the Williams College Museum of Art and other campus resources, students will not only experience firsthand the wide array of objects that have been produced within this vast geography, but will also come to recognize how multiple senses including sight, sound, smell, and touch play a key role in understanding how these objects work within their respective contexts. As tools of political control, social protest, divine manifestation, and spiritual intervention, these objects and their associated performances also challenge what we might typically consider art in the Western tradition and as such students will be pushed to think beyond such terms in their examinations of these rich creative traditions.',
        WMS_DISTRIB_NOTES: null
    },
    {
        WMS_ACAD_YEAR: '2020',
        OFFERED: 'N',
        STRM: '1193',
        CRSE_ID: '019563',
        EFFDT: '01-SEP-19',
        SUBJECT: 'AFR',
        CATALOG_NBR: '113',
        CLASS_SECTION: ' ',
        CLASS_NBR: '3820',
        CONSENT: 'N',
        GRADING_BASIS: 'OPT',
        SSR_COMPONENT: 'LEC',
        DESCR: 'Musics of Africa',
        UNITS_MINIMUM: '1',
        COURSE_TITLE_LONG: 'Musics of Africa',
        WMS_FIRST_NAME1: 'Corinna',
        WMS_MID_NAME1: 'S.',
        WMS_LAST_NAME1: 'Campbell',
        URL_1: 'https://music.williams.edu/profile/csc3',
        WMS_FIRST_NAME2: ' ',
        WMS_MID_NAME2: ' ',
        WMS_LAST_NAME2: ' ',
        URL_2: ' ',
        WMS_FIRST_NAME3: ' ',
        WMS_MID_NAME3: ' ',
        WMS_LAST_NAME3: ' ',
        URL_3: ' ',
        WMS_FIRST_NAME4: ' ',
        WMS_MID_NAME4: ' ',
        WMS_LAST_NAME4: ' ',
        URL_4: ' ',
        WMS_FIRST_NAME5: ' ',
        WMS_MID_NAME5: ' ',
        WMS_LAST_NAME5: ' ',
        URL_5: ' ',
        WMS_FIRST_NAME6: ' ',
        WMS_MID_NAME6: ' ',
        WMS_LAST_NAME6: ' ',
        URL_6: ' ',
        WMS_STND_MTG_PAT1: ' ',
        WMS_START_TIME1: ' ',
        WMS_END_TIME1: ' ',
        WMS_FACIL_DESCR1: ' ',
        WMS_STND_MTG_PAT2: ' ',
        WMS_START_TIME2: ' ',
        WMS_END_TIME2: ' ',
        WMS_FACIL_DESCR2: ' ',
        WMS_STND_MTG_PAT3: ' ',
        WMS_START_TIME3: ' ',
        WMS_END_TIME3: ' ',
        WMS_FACIL_DESCR3: ' ',
        WMS_ATTR_SRCH: 'DIV_D1,GBST_GBSTAFR,MUS_MUSW',
        WMS_CLASS_FORMAT: 'lecture/discussion',
        WMS_RQMT_EVAL:
            'grade based on a listening journal, bi-weekly short assignments, a final paper, and class participation',
        WMS_EXTRA_INFO: ' ',
        WMS_EXTRA_INFO2: ' ',
        WMS_INSTR_OTH: ' ',
        WMS_PREREQS: 'no prerequisites: prior musical background is not essential for this class',
        WMS_ENRL_PREF: 'current or prospective Music majors and Africana Studies concentrators',
        WMS_DEPT_NOTES: ' ',
        WMS_MATL_FEE: ' ',
        WMS_EXP_ENRL: '12',
        WMS_ENRL_LIMIT: '20',
        WMS_NC: ' ',
        CAMPUS: ' ',
        WMS_DESCR140: ' ',
        WMS_SHORT_DESCR: null,
        WMS_DISTRIB_NT1: null,
        WMS_DISTRIB_NT2: null,
        WMS_DISTRIB_NT3: null,
        WMS_DESCR_SRCH:
            'This course introduces a selection of musical cultures from the geographical breadth of Africa. Following an introductory exploration of the fundamental aesthetic and social parameters governing African musical practice, we will engage in a series of case studies considering a diverse array of musical practices and related social and political issues in specific locales. Featured countries include Ghana, Zimbabwe, Ethiopia, Algeria and the Democratic Republic of Congo. This course samples a wide range of musical practices from the Ghanaian dance craze, azonto, to Ethiopian liturgical chants, to Shona mbira music in Zimbabwe. Performance analysis and critical reading and listing assignments are combined with a number of hands-on workshops and musical exercises.',
        WMS_DISTRIB_NOTES: null
    }
];

function courseReducer(state = INITIAL_CATALOG, action) {
    switch (action.type) {
        default:
            return state;
    }
}

export default courseReducer;
